---
- name: Install Zabbix Agent
  hosts: all
  become: yes

  tasks:
    - name: Download Zabbix Repository Package
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb"
        dest: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"

    - name: Install Zabbix Repository Package
      apt:
        deb: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"
        state: present

    - name: Update Package List
      apt:
        update_cache: yes

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent2
        state: present

    - name: Copy Zabbix Agent Configuration File
      template:
        src: templates/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify:
        - restart zabbix-agent

  handlers:
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
