---
- name: Install Zabbix Agent
  hosts: your_target_host
  become: yes

  tasks:
    - name: Install Zabbix Agent Repository
      apt_repository:
        repo: 'deb http://repo.zabbix.com/zabbix/6.0/ubuntu focal main'
        state: present
        filename: 'zabbix'
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Zabbix Agent Repository
      yum_repository:
        name: zabbix
        description: Zabbix Official Repository - $basearch
        baseurl: 'http://repo.zabbix.com/zabbix/6.0/rhel/$releasever/$basearch/'
        gpgcheck: yes
        gpgkey: 'https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX'
        enabled: yes
      when: ansible_os_family == 'RedHat'

    - name: Install Zabbix Agent
      package:
        name: zabbix-agent
        state: present

    - name: Copy Zabbix Agent Configuration File
      template:
        src: templates/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify:
        - restart zabbix-agent

  handlers:
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
